### ISSUE TITLE
Wazuh Dashboards for OpenSearch integration shows errors

### ISSUE THREAD

**Issue by mateocervilla** [wazuh/wazuh-dashboard-plugins#5878] opened 2023-09-11 15:04 UTC
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | Alpha 1 | Firefox |

**Description**
During the testing of release `4.6.0`, in the `Opensearch integration` tests, we can observe that some panels of the dashboard provided by wazuh have errors: https://github.com/wazuh/wazuh/issues/18856#issuecomment-1712188259

**Steps to reproduce**
https://github.com/wazuh/wazuh-kibana-app/issues/5878#issuecomment-1714657593

**Screenshots**
![Screenshot from 2023-09-08 17-26-18](https://github.com/wazuh/wazuh/assets/68401037/8aa7dca6-ca0b-4efd-a9e1-53b84b89501a)
![Screenshot from 2023-09-08 17-29-01](https://github.com/wazuh/wazuh/assets/68401037/0eba7e7b-e970-4ab8-8a8a-5873a0aa11da)

**Additional context**

- VM created using `Vagrant`:
    - RAM: 8 GB 
    - 4 CPUs
    - `Debian` 12 Bookworm

- `Opensearch` version `2.9.0`
- `Wazuh Dashboards for OpenSearch` downloaded from https://packages-dev.wazuh.com/integrations/opensearch/4.x-2.x/dashboards/wz-os-4.x-2.x-dashboards.ndjson

**Comment by mateocervilla** [comment] 2023-09-11 22:14
I reproduced this steps again and have the same errors. Tested on `Ubuntu 22.04` and `Debian 12`.
I simplify the steps so it is quicker to replicate. Only install `Wazuh-Manager` to get alerts.

## Install `OpenSearch` and `OpenSearch-Dashboard`

```console
sudo apt-get update && sudo apt-get -y install lsb-release ca-certificates curl gnupg2
curl -o- https://artifacts.opensearch.org/publickeys/opensearch.pgp | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/opensearch-keyring
echo "deb [signed-by=/usr/share/keyrings/opensearch-keyring] https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-2.x.list
echo "deb [signed-by=/usr/share/keyrings/opensearch-keyring] https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.x/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-dashboards-2.x.list
sudo apt-get update
sudo apt-get install opensearch
sudo apt-get install opensearch-dashboards
```

## Edit `opensearch.yml` and `opensearch_dashboards.yml` for network access

In `/etc/opensearch/opensearch.yml` set:

- network.host: 0.0.0.0
- discovery.seed_hosts: ["127.0.0.1"]

In `/etc/opensearch-dashboards/opensearch_dashboards.yml` set:

- server.host: "0.0.0.0"

## Start services
```console
systemctl restart opensearch
systemctl restart opensearch-dashboards
```

## Import `Wazuh` dashboards on `Opensearch-Dashboards`

1. Menu
2. Dashboards Management
3. Saved Objects
4. Import
5. Select file and import

## Install `Wazuh-Manager`

```console
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
apt-get update
apt-get -y install wazuh-manager
systemctl start wazuh-manager
```

## Install Logstash

```console
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elastic-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
sudo apt-get update && sudo apt-get install logstash
sudo /usr/share/logstash/bin/logstash-plugin install logstash-output-opensearch
mkdir /etc/logstash/templates/
curl -o /etc/logstash/templates/wazuh.json https://packages-dev.wazuh.com/integrations/opensearch/4.x-2.x/dashboards/wz-os-4.x-2.x-template.json
touch /etc/sysconfig/logstash
echo 'LOGSTASH_KEYSTORE_PASS="logstashpassword"' > /etc/sysconfig/logstash
export LOGSTASH_KEYSTORE_PASS=logstashpassword
chown root /etc/sysconfig/logstash
chmod 600 /etc/sysconfig/logstash
systemctl start logstash
```
Configure passwords:
```console
sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash create
sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash add OPENSEARCH_USERNAME
```
- write `admin`
```console
sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash add OPENSEARCH_PASSWORD
```
- write `admin`

## Configure pipeline

```console
touch /etc/logstash/conf.d/wazuh-opensearch.conf
```

Edit `/etc/logstash/conf.d/wazuh-opensearch.conf` :

```
input {
  file {
    id => "wazuh_alerts"
    codec => "json"
    start_position => "beginning"
    stat_interval => "1 second"
    path => "/var/ossec/logs/alerts/alerts.json"
    mode => "tail"
    ecs_compatibility => "disabled"
  }
}

output {
    opensearch {
      hosts => ["localhost:9200"]
      auth_type => {
         type => 'basic'
         user => '${OPENSEARCH_USERNAME}'
         password => '${OPENSEARCH_PASSWORD}'
      }
      index  => "wazuh-alerts-4.x-%{+YYYY.MM.dd}"
      ssl_certificate_verification => false
      ssl => true
      template => "/etc/logstash/templates/wazuh.json"
      template_name => "wazuh"
      template_overwrite => true
    }
}
```

## Start Logstash

```console
sudo systemctl stop logstash
sudo -E /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/wazuh-opensearch.conf --path.settings /etc/logstash/
```

## Check Dashboards

1. Menu
2. Dashboards
3. Select one (`wazuh-security-events-v1.0`)

**Comment by chantal-kelm** [comment] 2023-09-12 10:52
I have tried to reproduce the problem but it works correctly. 

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/fd06e13e-b4dc-4164-ba61-f18af670e077">

We will continue to work to find out why in @mateocervilla' environment the error occurs.

**Comment by chantal-kelm** [comment] 2023-09-13 18:46
My colleague @mateocervilla has set up a server and by sharing it with me I was able to see and investigate what was going on in his environment.
I was able to see that the problem was that the index was not taking the mappings defined in the template and so was showing the following error in the visualizations:

> Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [agent.name] in order to load field data by uninverting the inverted index. Note that this can use significant memory.

After creating a new index and re-indexing, the problem is solved.

![image (1)](https://github.com/wazuh/wazuh-kibana-app/assets/99441266/0fe9bb47-4586-4ea2-8cf9-586cb34c6238)

**Comment by gdiazlo** [comment] 2023-09-14 09:47
We're closing this as it was due to the configuration of the environment. It is not clear how we reached the point on which this failed. We need to test this again in Beta1.

**Comment by mateocervilla** [comment] 2024-01-12 15:28
We reopen this issue since it is still happening in testing 4.8.0: https://github.com/wazuh/wazuh/issues/21384#issuecomment-1889467638

The testing was carried out on a completely different machine and with a different OS.

I don't remember well but I think they had previously mentioned that there was an error in some template file. If so, it was not updated either in its link or in the documentation.

I recommend that you follow the instructions step by step in a virtual machine, using the links provided by the documentation to be able to replicate it.

**Comment by chantal-kelm** [comment] 2024-01-19 17:49
We have been able to reproduce the error:

![image (1)](https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/7edd8619-143f-42e2-8ea5-ccae717841d8)

Reviewing the template with my colleague @Desvelao that we accessed from Opensearch devTools we saw that the template did not have any settings and mappings.
I remembered that this happened when a necessary setting was not included in the configuration of logstash `legacy_template => false`, so I added this setting, and did a reindexing, with which I was able to solve the error.

**Closed** 2024-01-23 16:44 UTC
Labels: level/task, type/troubleshooting
