### ISSUE TITLE
Wazuh dashboards for Splunk integration do not display correctly using dark mode

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-dashboard-plugins#6334] opened 2024-01-17 10:26 UTC
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | Alpha2 | Chrome |

**Description**

As shown in the tests of the following issue, it can be seen that in two of the custom dashboards for Splunk, some panels do not appear correctly when using the dark style:
- https://github.com/wazuh/wazuh/issues/21383#issuecomment-1894230086

**Preconditions**
N/A

**Steps to reproduce**
Follow the steps of the documentation as they have been done in the issue:
- https://documentation-dev.wazuh.com/v4.8.0-alpha2/integrations-guide/splunk/index.html
- https://github.com/wazuh/wazuh/issues/21383

**Expected Result**
1. Display panels in dark style.

**Actual Result** + **Screenshots**
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/37207742/f46ef780-4efe-4d61-b0f9-9c85206d6714)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/37207742/332e9010-a172-4f7c-9da2-5672689e8ee1)

**Comment by Tostti** [comment] 2024-01-19 15:30
Confirmed the issue. After testing the cause of the issue was identified and solved. 

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/bf6cb625-b65f-4d64-aedd-309bec211cbe)
![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/c0760f0f-ecdd-493f-a754-ff868ec200ee)

After the fix, no errors were found in any of the Dashboards. 

Currently waiting for https://github.com/wazuh/wazuh-dashboard-plugins/issues/5878 to be completed, as both issues require to upload new dashboards.

**Comment by Tostti** [comment] 2024-01-23 16:03
Changes merged to the corresponding repository. Waiting for the new dashboards to be uploaded so the users can use them 
https://github.com/wazuh/internal-devel-requests/issues/711

**Comment by Tostti** [comment] 2024-01-23 16:29
The new dashboars were uploaded. Closing this issue

**Closed by Tostti** 2024-01-23 16:29 UTC
Labels: type/bug, level/task
