### ISSUE TITLE
Console error about PNG image in the `devTools` tab

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-dashboard-plugins#6218] opened 2023-12-14 12:01 UTC
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.7.0 OVA | 03 | Brave |

**Description**

While trying to reproduce the error reported in the issue https://github.com/wazuh/wazuh-dashboard-plugins/issues/6211 I have found a console error regarding an icon

```
Error while trying to use the following icon from the Manifest: https://192.168.56.19/android-chrome-129x19 wazuh#/wazuh-dev?tab=devTools:12.png (Download error or resource isn't a valid image)
```

It is necessary to determine if it is our problem or not

**Preconditions**
1. -

**Steps to reproduce**
Same as https://github.com/wazuh/wazuh-dashboard-plugins/issues/6211

**Expected Result**
1. No PNG image error must be obtained

**Actual Result**
1. Console error about PNG image

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/14913942/a20bfdd9-e0be-45b6-a9ab-03e18fcd7ecc)

**Comment by Tostti** [comment] 2023-12-14 20:10
Hello @rauldpm, I've been testing this issue using the same specifications that you provided (Wazuh OVA 4.7.0 03, brave browser) and was not able to reproduce the issue after a long time.
Are you still able to reproduce it? Do you have more information or specific steps to reproduce it? 

Regards,

**Comment by gdiazlo** [comment] 2024-01-16 14:13
If we're unable to reproduce the error, let's close this and reopen it in case if appears again.

**Closed by gdiazlo** 2024-01-16 14:13 UTC
Labels: type/bug, level/task
